import "./../Submodules/WeTransfer-iOS-CI/Fastlane/Fastfile"

desc "Run the tests and prepare for Danger"
lane :test do |options|
  test_package(
        package_name: 'AirSettingsUI',
        package_path: './',
        scheme: "AirSettingsUI",
				destination: 'platform=iOS Simulator,name=iPhone SE (3rd generation)'
  )
end